import sys
import os

# Add paths
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
sys.path.append(current_dir)
sys.path.append(parent_dir)

from simulator.profiler import PerformanceProfiler

def run_profiling_demo():
    print("[Profiler] Hive-Reflex Profiling Demo")
    
    # 1. Create Dummy MobileNet Config
    # Represents the JSON generated by codegen_cim.py
    mobilenet_config = {
        'model_name': 'MobileNetV1_Tiny',
        'layers': [
            {'name': 'conv1', 'type': 'fc', 'shape': '(32, 27)'},  # Approx Conv 3x3x3 -> 27 inputs per kernel
            {'name': 'dw1',   'type': 'fc', 'shape': '(1, 9)'},     # Depthwise 3x3 -> 9 inputs (Parallelized later)
            {'name': 'pw1',   'type': 'fc', 'shape': '(64, 32)'},   # Pointwise 1x1
            {'name': 'dw2',   'type': 'fc', 'shape': '(1, 9)'},
            {'name': 'pw2',   'type': 'fc', 'shape': '(128, 64)'},
            # Output Classifier
            {'name': 'fc_out','type': 'fc', 'shape': '(10, 512)'}
        ]
    }
    
    # 2. Init Profiler
    # 256 MACs, 100 MHz clock
    profiler = PerformanceProfiler(mac_array_size=256, frequency_mhz=100)
    
    # 3. Run
    profiler.profile_model(mobilenet_config)
    
    # 4. Export
    profiler.export_report("profiling_report.csv")

if __name__ == "__main__":
    run_profiling_demo()
