#!/usr/bin/env python3
"""
Digital Twin Firmware for Hive-Reflex SoC
Generated by codegen_cim.py
"""
import sys
import os
import numpy as np
import time
# Ensure simulator is importable
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'simulator'))
sys.path.append(os.path.join(os.path.dirname(__file__), '..')) # fallback
try:
    from simulator.sim_reflex import SimReflex
except ImportError:
    from sim_reflex import SimReflex

# Memory Constraints (64KB)
SRAM_SIZE = 64 * 1024
sim = SimReflex(sram_size_kb=64)

def calibrate_system():
    print('[SoC-FW] Starting On-Chip Calibration...')
    # Simulate hardware check
    # In real HW: run known pattern through CIM, check ADC offset
    time.sleep(0.1)
    # Apply compensation
    sim.registers['CIM_CALIB'] = 0xAA
    print('[SoC-FW] Calibration Complete. Offset adjusted.')

def run_inference(input_data):
    print('[SoC-FW] Starting Inference...')
    print(f'  > Input Shape: {input_data.shape}')
    start_t = time.time()
    # Write Input to SRAM
    sim.mem_write(0, input_data.tobytes())
    # Layer: fc1 ((10, 10))
    sim.cim_fully_connected(0, 16384, 0, 10, 10, relu=1)
    end_t = time.time()
    print(f'[SoC-FW] Inference Done. Time: {(end_t-start_t)*1000:.2f}ms')
    # Read Output (Assuming last layer size (10, 10))
    output_bytes = sim.mem_read(16384, 40)
    output = np.frombuffer(output_bytes, dtype=np.float32)
    return output

def main():
    print('--- Hive-Reflex Digital Twin Booting ---')
    sim.stats['cycles'] = 0
    
    # 0. System Calibration
    calibrate_system()
    
    # Mock Sensor Loop
    for i in range(3):
        print(f'\n[SoC-FW] Iteration {i}')
        # 1. Read Sensor (Mock)
        print('  > Reading Sensors...')
        input_sample = np.random.randn(10).astype(np.float32)
        
        # 2. Run Inference
        result = run_inference(input_sample)
        
        # 3. Actuate (Mock)
        pred = np.argmax(result)
        print(f'  > Actuation: Class {pred} (Conf: {result[pred]:.2f})')
    
    print('\n[SoC-FW] System Halted.')
    print(f'Total Simulated Cycles: {int(sim.stats["cycles"])}')

if __name__ == '__main__':
    main()