import math

class RTLPruner:
    """
    Analyzes the model requirements to prune the hardware description (RTL).
    Generates a Verilog header file (soc_config.vh) to configure the SoC.
    """
    def __init__(self, layers, peak_memory_usage):
        self.layers = layers
        self.peak_memory_usage = peak_memory_usage
        self.config = {}

    def analyze(self):
        """
        Analyze the layers to determine required hardware blocks.
        """
        self.config['HAS_CONV'] = 0
        self.config['HAS_FC'] = 0
        self.config['HAS_TRANSFORMER'] = 0
        self.config['HAS_ACTIVATION'] = 0
        
        # Analyze Operations
        for layer in self.layers:
            op_type = layer.get('op_type', '')
            if op_type in ['Conv']:
                self.config['HAS_CONV'] = 1
            elif op_type in ['Gemm', 'MatMul']:
                self.config['HAS_FC'] = 1
            elif op_type in ['Softmax', 'LayerNormalization']:
                self.config['HAS_TRANSFORMER'] = 1
            elif op_type in ['Relu', 'Sigmoid', 'Tanh', 'Gelu']:
                self.config['HAS_ACTIVATION'] = 1
        
        # Analyze Memory
        # Assume 1 Bank = 32KB
        bank_size_kb = 32
        required_kb = math.ceil(self.peak_memory_usage / 1024)
        num_banks = math.ceil(required_kb / bank_size_kb)
        
        # Ensure minimum 1 bank
        num_banks = max(1, num_banks)
        
        # Determine address width based on total size
        total_size_bytes = num_banks * bank_size_kb * 1024
        addr_width = math.ceil(math.log2(total_size_bytes))

        self.config['SRAM_NUM_BANKS'] = num_banks
        self.config['SRAM_ADDR_WIDTH'] = addr_width
        self.config['TOTAL_SRAM_KB'] = num_banks * bank_size_kb

    def parse_io_config(self, config_path):
        """
        Parse IO configuration from JSON
        """
        import json
        import os
        
        self.config['IO_I2C'] = 0
        self.config['IO_SPI'] = 0
        self.config['IO_UART'] = 0
        self.config['IO_GPIO_COUNT'] = 0
        
        if config_path and os.path.exists(config_path):
            try:
                with open(config_path, 'r') as f:
                    io_conf = json.load(f)
                    
                self.config['IO_I2C'] = io_conf.get('i2c_count', 0)
                self.config['IO_SPI'] = io_conf.get('spi_count', 0)
                self.config['IO_UART'] = io_conf.get('uart_count', 0)
                self.config['IO_GPIO_COUNT'] = io_conf.get('gpio_count', 0)
                print(f"[RTL Pruner] Loaded IO Config: {config_path}")
            except Exception as e:
                print(f"[RTL Pruner] Error loading IO config: {e}")

    def generate_config(self, output_path):
        """
        Generate soc_config.vh
        """
        with open(output_path, 'w') as f:
            f.write("// Hive-Reflex SoC Configuration\n")
            f.write("// Generated by HardwarePruner\n")
            f.write("// Based on Application Requirements\n\n")
            
            f.write("`ifndef SOC_CONFIG_VH\n")
            f.write("`define SOC_CONFIG_VH\n\n")
            
            f.write("// --- Memory Configuration ---\n")
            f.write(f"`define SRAM_NUM_BANKS {self.config['SRAM_NUM_BANKS']}\n")
            f.write(f"`define SRAM_ADDR_WIDTH {self.config['SRAM_ADDR_WIDTH']}\n")
            f.write(f"// Total SRAM Size: {self.config['TOTAL_SRAM_KB']} KB\n\n")
            
            f.write("// --- Accelerator Configuration ---\n")
            if self.config.get('HAS_CONV'):
                f.write("`define ENABLE_CIM_CONV_ENGINE\n")
            else:
                f.write("// `define ENABLE_CIM_CONV_ENGINE // Pruned: Not required\n")
                
            if self.config.get('HAS_FC'):
                f.write("`define ENABLE_CIM_GEMM_ENGINE\n")
            else:
                f.write("// `define ENABLE_CIM_GEMM_ENGINE // Pruned: Not required\n")

            if self.config.get('HAS_TRANSFORMER'):
                f.write("`define ENABLE_CIM_TRANSFORMER_ACCEL\n")
            else:
                f.write("// `define ENABLE_CIM_TRANSFORMER_ACCEL // Pruned: Not required\n")

            f.write("\n// --- IO Configuration ---\n")
            if self.config.get('IO_I2C', 0) > 0:
                f.write(f"`define ENABLE_I2C\n`define I2C_COUNT {self.config['IO_I2C']}\n")
            else:
                f.write("// `define ENABLE_I2C // Pruned\n")

            if self.config.get('IO_SPI', 0) > 0:
                f.write(f"`define ENABLE_SPI\n`define SPI_COUNT {self.config['IO_SPI']}\n")
            else:
                f.write("// `define ENABLE_SPI // Pruned\n")

            if self.config.get('IO_UART', 0) > 0:
                f.write(f"`define ENABLE_UART\n`define UART_COUNT {self.config['IO_UART']}\n")
            else:
                f.write("// `define ENABLE_UART // Pruned\n")
                
            f.write(f"`define GPIO_COUNT {self.config.get('IO_GPIO_COUNT', 0)}\n")

            f.write("\n// --- Power Gating Configuration ---\n")
            # Permanent Power Gating for unused domains (Logic Removal/Tie-off)
            if not self.config.get('HAS_CONV'):
                f.write("`define POWER_GATE_CONV_DOMAIN\n")
            else:
                f.write("// `define POWER_GATE_CONV_DOMAIN // Active\n")

            if not self.config.get('HAS_FC'):
                f.write("`define POWER_GATE_GEMM_DOMAIN\n")
            else:
                f.write("// `define POWER_GATE_GEMM_DOMAIN // Active\n")

            if not self.config.get('HAS_TRANSFORMER'):
                f.write("`define POWER_GATE_TRANSFORMER_DOMAIN\n")
            else:
                f.write("// `define POWER_GATE_TRANSFORMER_DOMAIN // Active\n")
            
            f.write("\n`endif // SOC_CONFIG_VH\n")
            
        print(f"[RTL Pruner] Generated {output_path}")
        print(f"  - SRAM Banks: {self.config['SRAM_NUM_BANKS']} ({self.config['TOTAL_SRAM_KB']} KB)")
        print(f"  - Conv Engine: {'Enabled' if self.config.get('HAS_CONV') else 'Pruned'}")
        print(f"  - Gemm Engine: {'Enabled' if self.config.get('HAS_FC') else 'Pruned'}")
        print(f"  - Transformer: {'Enabled' if self.config.get('HAS_TRANSFORMER') else 'Pruned'}")
        print(f"  - IO: I2C={self.config.get('IO_I2C',0)}, SPI={self.config.get('IO_SPI',0)}, GPIO={self.config.get('IO_GPIO_COUNT',0)}")

