/**
 * Hive-Reflex CIM Core - SystemC TLM-2.0 Model
 * Generated by systemc_exporter.py
 */

#ifndef CIM_CORE_H
#define CIM_CORE_H

#include <systemc.h>
#include <tlm.h>
#include <tlm_utils/simple_target_socket.h>

class CIM_Core : public sc_module {
public:
    // TLM Socket to receive transactions from CPU (RISC-V)
    tlm_utils::simple_target_socket<CIM_Core> socket;

    // Registers
    uint32_t REG_STATUS;
    uint32_t REG_CTRL;
    
    // Config
    static const int MAC_ARRAY_SIZE = 1024;
    static const int SRAM_SIZE_KB = 256;

    SC_CTOR(CIM_Core) : socket("socket") {
        // Register Callbacks
        socket.register_b_transport(this, &CIM_Core::b_transport);
        SC_THREAD(compute_process);
        
        REG_STATUS = 0;
        REG_CTRL = 0;
    }

private:
    void b_transport(tlm::tlm_generic_payload& trans, sc_time& delay);
    void compute_process();
    
    // Internal Memory (Mock)
    std::vector<uint8_t> sram;
};

#endif // CIM_CORE_H
